opt_type: "spatialgen_sd21"

opt:
  dataset_name: "spatiallm"
  test_data_dir: "<put your spatiallm-testset data folder here/>"
  test_split_file: "put your spatiallm-testset data folder here/test_split.txt"

optimizer:
  name: "adamw"
  lr: 0.0001
  betas:
    - 0.9
    - 0.999
  weight_decay: 0.01
  eps: 1.e-8

lr_scheduler:
  name: "constant_warmup"
  num_warmup_steps: 1000

train:
  batch_size_per_gpu: 1
  epochs: 1000
  log_freq: 50
  early_eval_freq: 100
  eval_freq: 1000
  save_freq: 500
  eval_freq_epoch: 10
  save_freq_epoch: 10
  ckpts_total_limit: 10
  ema_kwargs:
    decay: 0.9999
    use_ema_warmup: true
    inv_gamma: 1.
    power: 0.75

val:
  batch_size_per_gpu: 1
